version: '3.9'

services:
  postgres:
    image: postgres:17.4
    container_name: postgres_inventory_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
  restful-service:
    container_name: spring_restful
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: